// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-organization.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_organization_default = defineTool({
  name: "get_organization",
  title: "Get organization info",
  description: "Get information about the Association Ivoirienne d'Astronomie (AIA): mission, founding, and location.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify({
          name: "Association Ivoirienne d'Astronomie (AIA)",
          founded: 2021,
          city: "Abidjan",
          country: "C\xF4te d'Ivoire",
          tagline: "Faisons briller les \xE9toiles au c\u0153ur de l'Afrique",
          summary: "Organisation scientifique fond\xE9e en 2021 \xE0 Abidjan qui vulgarise l'astronomie et d\xE9veloppe la culture scientifique et spatiale en C\xF4te d'Ivoire.",
          website: "https://astroivoire.lovable.app"
        })
      }
    ]
  })
});

// src/lib/mcp/tools/list-missions.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_missions_default = defineTool2({
  name: "list_missions",
  title: "List AIA missions",
  description: "List the core missions of the Association Ivoirienne d'Astronomie.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify([
          { title: "Vulgariser les sciences de l'univers", description: "Rendre l'astronomie accessible \xE0 tous les publics" },
          { title: "Sensibiliser les jeunes", description: "Inspirer les futures g\xE9n\xE9rations aux carri\xE8res spatiales" },
          { title: "Organiser des observations", description: "Conf\xE9rences et s\xE9ances d'observation astronomique" },
          { title: "Favoriser l'inclusion", description: "Promouvoir la parit\xE9 dans les domaines scientifiques" }
        ])
      }
    ]
  })
});

// src/lib/mcp/tools/list-activities.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_activities_default = defineTool3({
  name: "list_activities",
  title: "List AIA activities",
  description: "List the main activities and programs run by the Association Ivoirienne d'Astronomie.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify([
          {
            title: "AstroTour C\xF4te d'Ivoire",
            description: "Tourn\xE9e scientifique dans les villes du pays pour sensibiliser le grand public, les jeunes et les \xE9l\xE8ves \xE0 l'astronomie."
          },
          {
            title: "Soir\xE9es d'observation",
            description: "\xC9v\xE9nements publics pour observer la Lune, les \xE9toiles et les plan\xE8tes avec des t\xE9lescopes accessibles \xE0 tous."
          },
          {
            title: "AstroPause",
            description: "Conf\xE9rences \xE0 l'universit\xE9 pour d\xE9battre des enjeux du spatial ivoirien et africain."
          },
          {
            title: "Ateliers scolaires",
            description: "S\xE9ances \xE9ducatives dans les \xE9coles pour initier les plus jeunes \xE0 l'astronomie."
          }
        ])
      }
    ]
  })
});

// src/lib/mcp/tools/list-events.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_events_default = defineTool4({
  name: "list_upcoming_events",
  title: "List upcoming events",
  description: "List upcoming AIA events (observations, tours, trainings).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify([
          { date: "12 juillet 2025", title: "Nuit de la Lune", location: "UFR SSMT, Abidjan", type: "Observation", status: "\xC0 venir" },
          { date: "Septembre 2025", title: "AstroTour II", location: "Bouak\xE9, Yamoussoukro, Korhogo", type: "Tourn\xE9e", status: "Planifi\xE9" },
          { date: "Novembre 2025", title: "Formation enseignants", location: "Abidjan", type: "Formation", status: "Inscription ouverte" }
        ])
      }
    ]
  })
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_contact_default = defineTool5({
  name: "get_contact",
  title: "Get contact info",
  description: "Get AIA contact information: email, address, and social links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify({
          email: "associationivoirienneastro@gmail.com",
          address: "UFR SSMT, Universit\xE9 F\xE9lix Houphou\xEBt-Boigny, Cocody, Abidjan, C\xF4te d'Ivoire",
          social: {
            facebook: "https://www.facebook.com/Association.Ivoirienne.Astronomie"
          }
        })
      }
    ]
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "aia-mcp",
  title: "AIA \u2014 Association Ivoirienne d'Astronomie",
  version: "0.1.0",
  instructions: "Public MCP server for the Association Ivoirienne d'Astronomie (AIA). Use these tools to answer questions about AIA's mission, activities, upcoming events, and contact info.",
  tools: [get_organization_default, list_missions_default, list_activities_default, list_events_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
